// <auto-generated />
using System;
using Forum.App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Forum.App.Data.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    [Migration("20230610175055_CreateAndSeedDb")]
    partial class CreateAndSeedDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Forum.App.Data.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d45dbbe-a6fb-4b16-9e29-5c21e2f8229d"),
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam scelerisque vulputate nibh, quis euismod diam consequat in. Nullam at nulla. ",
                            Title = "My first post"
                        },
                        new
                        {
                            Id = new Guid("f2ecebb6-1b93-4f49-b6fe-a4c998c9b9d3"),
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris commodo elit id erat fringilla luctus. ",
                            Title = "My second post"
                        },
                        new
                        {
                            Id = new Guid("f58ae873-7133-4464-92ab-051691bc0e99"),
                            Content = "Consectetur adipiscing elit. Mauris commodo elit id erat fringilla luctus. ",
                            Title = "My third post"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
